name: telematics_sdk_example
description: Demonstrates how to use the telematics_sdk plugin.
publish_to: none
version: 0.0.2+15

environment:
  sdk: ">=3.10.0 <4.0.0"
  flutter: ">=3.38.0"

dependencies:
  flutter:
    sdk: flutter

  telematics_sdk:
    path: ../
  uuid: ^4.3.2

flutter:
  uses-material-design: true
