name: telematics_sdk
version: 0.3.3
description: A Flutter plugin for integration Telematics SDK in Android and iOS applications.
homepage: https://docs.telematicssdk.com
repository: https://github.com/Mobile-Telematics/telematicsSDK-demoapp-flutter-
issue_tracker: https://github.com/Mobile-Telematics/telematicsSDK-demoapp-flutter-/issues

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.16.0"

flutter:
  plugin:
    platforms:
      android:
        package: com.telematicssdk
        pluginClass: TelematicsSDKPlugin
      ios:
        pluginClass: TelematicsSDKPlugin
